"""Pydantic schemas for Trading Consultation Subsystem, A/B Testing, and Testnet Support."""

from datetime import datetime
from typing import Any, Literal
from uuid import uuid4

from pydantic import BaseModel, Field, model_validator


class TradingTelemetry(BaseModel):
    """Real-time performance telemetry emitted by the trading bot."""
    equity: float = Field(description="Current account equity in USDT")
    unrealized_pnl: float = Field(description="Current floating PnL of open positions")
    realized_pnl: float = Field(description="Cumulative realized profit/loss")
    win_rate: float = Field(ge=0.0, le=1.0, description="Historical win rate fraction between 0.0 and 1.0")
    profit_factor: float = Field(description="Gross profits divided by gross losses")
    max_drawdown_pct: float = Field(description="Peak-to-trough drawdown percentage")
    consecutive_losses: int = Field(ge=0, description="Current consecutive losing trade count")
    total_trades: int = Field(ge=0, description="Total count of completed trades")
    sharpe_ratio: float | None = Field(default=None, description="Annualized or period Sharpe ratio")


class StrategyPerformance(BaseModel):
    """Performance breakdown for an individual algorithmic trading strategy."""
    strategy_name: str = Field(description="Identifier or name of the strategy (e.g. Supertrend, EMA_Cross)")
    trade_count: int = Field(ge=0, description="Trades executed by this specific strategy")
    win_rate: float = Field(ge=0.0, le=1.0, description="Strategy win rate fraction (0.0 - 1.0)")
    profit_factor: float = Field(description="Strategy profit factor")
    net_pnl: float = Field(description="Net realized PnL generated by this strategy")
    avg_win: float = Field(description="Average profit on winning trades")
    avg_loss: float = Field(description="Average loss on losing trades")
    consecutive_losses: int = Field(ge=0, description="Current consecutive losses for this strategy")


class TestnetContext(BaseModel):
    """Testnet-specific exchange environment telemetry and live risk state."""
    testnet_equity: float = Field(description="Current testnet wallet balance / equity in USDT")
    testnet_drawdown_pct: float = Field(description="Current drawdown percentage on testnet")
    testnet_daily_loss: float = Field(default=0.0, description="Realized loss accrued during current 24h cycle")
    testnet_open_positions: int = Field(ge=0, default=0, description="Number of currently active testnet positions")
    testnet_margin_level: float = Field(default=100.0, description="Current account margin level percentage")


class TradingConsultRequest(BaseModel):
    """Advisory request submitted by an autonomous trading bot instance."""
    bot_id: str = Field(description="Unique identifier of the consulting bot instance")
    trading_mode: Literal["PAPER", "TESTNET"] = Field(description="Operational mode (only non-live modes allowed)")
    testnet_specific: TestnetContext | None = Field(
        default=None,
        description="Testnet-specific live exchange state when operating on testnet"
    )
    experiment_id: str | None = Field(default=None, description="Optional experiment tracking identifier")
    experiment_group: Literal["CONTROL", "TREATMENT"] | None = Field(
        default=None,
        description="A/B testing arm identifier (CONTROL or TREATMENT)"
    )
    control_metrics: dict[str, Any] | None = Field(
        default=None,
        description="Baseline metrics from the control arm for comparison analysis"
    )
    telemetry: TradingTelemetry = Field(description="High-level account and performance telemetry")
    strategy_performance: list[StrategyPerformance] = Field(default_factory=list, description="Per-strategy performance telemetry")
    current_parameters: dict[str, dict[str, Any]] = Field(
        default_factory=dict,
        description="Current live parameters: strategy_name -> parameter_name -> current_value"
    )
    regime_data: dict[str, Any] | None = Field(default=None, description="Market regime indicators, volatility, trend state")
    recent_trades: list[dict[str, Any]] | None = Field(
        default=None,
        description="Last 10-20 closed trades with entry, exit, pnl, side, duration"
    )
    consultation_reason: Literal["SCHEDULED", "DRAWDOWN_EVENT", "LOSS_STREAK", "MANUAL"] = Field(
        description="Trigger context for requesting advisory consultation"
    )


class ParameterChange(BaseModel):
    """Bounded parameter calibration recommendation."""
    strategy: str = Field(description="Target strategy name")
    parameter: str = Field(description="Parameter key name (e.g. stop_loss_pct, atr_multiplier)")
    current_value: Any = Field(description="Current value before recommendation")
    recommended_value: Any = Field(description="New recommended value proposed by consultation")
    change_pct: float = Field(description="Computed percentage change relative to current value")
    rationale: str = Field(description="Evidence-based reasoning derived from multi-agent debate")


class AIUniverseDecision(BaseModel):
    """Final structured advisory decision produced by Inference."""
    decision_id: str = Field(default_factory=lambda: str(uuid4()), description="Unique UUID for this advisory decision")
    timestamp: str = Field(
        default_factory=lambda: datetime.utcnow().isoformat(),
        description="ISO 8601 creation timestamp"
    )
    status: Literal["RECOMMENDATION", "NO_CHANGE", "INSUFFICIENT_DATA"] = Field(
        description="Advisory status outcome"
    )
    confidence: float = Field(ge=0.0, le=1.0, description="Confidence score in the recommendation (0.0 to 1.0)")
    parameter_changes: list[ParameterChange] = Field(
        default_factory=list,
        description="Bounded parameter changes (maximum 2, prefer 1)"
    )
    risk_assessment: str = Field(description="Narrative assessment of current drawdown, risk, and downside exposure")
    regime_analysis: str = Field(description="Interpretation of market regime data, volatility, or market trends")
    dissent_notes: str = Field(description="Critiques, dissent, or counter-risks raised by the Critic agent")
    debate_summary: str = Field(description="Condensed multi-agent deliberation trail across specialists")
    valid_until: str = Field(description="ISO 8601 expiration timestamp for this advisory decision (default 24h)")
    # A/B testing fields
    comparison_rationale: str | None = Field(
        default=None,
        description="Detailed comparative rationale explaining how this recommendation differs from or relates to the control baseline"
    )
    expected_improvement: str | None = Field(
        default=None,
        description="Quantitative estimate of expected performance improvement based on historical telemetry"
    )
    treatment_status: str | None = Field(
        default=None,
        description="Performance status relative to control (e.g., OUTPERFORMING_CONTROL, PARITY, UNDERPERFORMING_CONTROL)"
    )
    # Testnet-specific fields
    testnet_risk_assessment: str | None = Field(
        default=None,
        description="Testnet-specific capital preservation analysis, margin level evaluation, and position sizing guidelines"
    )
    # 13 Canonical Response Fields for FRIDAY Universe Interoperability
    task_id: str = Field(default_factory=lambda: f"task_{uuid4().hex[:12]}")
    trace_id: str = Field(default_factory=lambda: f"trace_{uuid4().hex[:8]}")
    answer: str = Field(default="")
    reasoning_summary: str = Field(default="")
    uncertainty: float = Field(default=0.10)
    evidence: list[str] = Field(default_factory=list)
    agents_used: list[str] = Field(default_factory=lambda: ["trading_analyst", "critic", "synthesizer"])
    recommendations: list[str] = Field(default_factory=list)
    proposed_actions: list[dict[str, Any]] = Field(default_factory=list)
    authorization_required: bool = Field(default=True)
    provider_metadata: dict[str, Any] = Field(default_factory=lambda: {"provider": "trading_advisory_engine", "model": "quantitative_specialist"})
    failure_state: str | None = Field(default=None)

    @model_validator(mode="after")
    def populate_canonical_envelope_fields(self) -> "AIUniverseDecision":
        if not self.answer:
            self.answer = (
                f"Trading Consultation Advisory [{self.status}]: "
                f"{len(self.parameter_changes)} parameter calibration(s) proposed. "
                f"Risk Assessment: {self.risk_assessment}"
            )
        if not self.reasoning_summary:
            self.reasoning_summary = self.debate_summary or self.risk_assessment
        if not self.evidence:
            ev = []
            if self.risk_assessment:
                ev.append(self.risk_assessment)
            if self.regime_analysis:
                ev.append(self.regime_analysis)
            self.evidence = ev
        if not self.recommendations:
            self.recommendations = [pc.rationale for pc in self.parameter_changes] or [f"Status: {self.status}"]
        if not self.proposed_actions:
            actions = []
            for pc in self.parameter_changes:
                actions.append({
                    "action": f"calibrate_{pc.parameter}",
                    "target": "stratex_trading_bot",
                    "parameters": {
                        "strategy": pc.strategy,
                        "parameter": pc.parameter,
                        "current_value": pc.current_value,
                        "recommended_value": pc.recommended_value,
                        "change_pct": pc.change_pct,
                    },
                    "rationale": pc.rationale,
                    "is_executable_command": False,
                    "requires_authorization": True,
                    "risk_level": "medium" if abs(pc.change_pct) < 15.0 else "high",
                })
            self.proposed_actions = actions
        if self.status == "INSUFFICIENT_DATA" and not self.failure_state:
            self.failure_state = "INSUFFICIENT_DATA"
        self.uncertainty = round(1.0 - self.confidence, 4)
        return self


# --- A/B Experiment Tracking Schemas ---

class ExperimentStartRequest(BaseModel):
    """Payload to register and launch a new A/B trading experiment."""
    experiment_id: str = Field(description="Unique experiment identifier")
    hypothesis: str | None = Field(default=None, description="Hypothesis being evaluated in the experiment")
    duration_hours: float = Field(default=72.0, ge=1.0, description="Scheduled duration of the experiment in hours")
    success_metrics: list[str] = Field(
        default_factory=lambda: ["profit_factor", "win_rate", "max_drawdown_pct", "sharpe_ratio"],
        description="Key metrics used to determine the winning arm"
    )
    control_bot_id: str = Field(description="Bot instance identifier assigned to the CONTROL arm")
    treatment_bot_id: str = Field(description="Bot instance identifier assigned to the TREATMENT arm")
    initial_parameters: dict[str, Any] | None = Field(
        default_factory=dict,
        description="Baseline parameter configuration for both arms at experiment start"
    )


class ExperimentConfigResponse(BaseModel):
    """Response returned when an A/B experiment is successfully registered."""
    experiment_id: str
    status: Literal["ACTIVE", "COMPLETED", "TERMINATED"] = "ACTIVE"
    start_time: str
    duration_hours: float
    control_config: dict[str, Any]
    treatment_config: dict[str, Any]
    success_metrics: list[str]
    message: str = "A/B Experiment successfully initialized."


class ExperimentStatusResponse(BaseModel):
    """Current live progress and health status of an active A/B experiment."""
    experiment_id: str
    status: Literal["ACTIVE", "COMPLETED", "TERMINATED"]
    start_time: str
    elapsed_hours: float
    duration_hours: float
    active_arms: list[str]
    consultations_count: dict[str, int] = Field(
        default_factory=lambda: {"CONTROL": 0, "TREATMENT": 0},
        description="Count of consultations logged per arm"
    )
    latest_telemetry: dict[str, Any] | None = None


class ExperimentResultsResponse(BaseModel):
    """Aggregated results and performance analysis upon experiment completion."""
    experiment_id: str
    status: Literal["ACTIVE", "COMPLETED", "TERMINATED"]
    winner: Literal["CONTROL", "TREATMENT", "INCONCLUSIVE"] | None = None
    duration_hours: float
    control_summary: dict[str, Any]
    treatment_summary: dict[str, Any]
    comparison_analysis: dict[str, Any]
    conclusion: str


# --- Testnet Performance & Comparison Schemas ---

class TestnetPerformanceResponse(BaseModel):
    """Aggregated performance metrics comparing TESTNET consultations against PAPER trading."""
    total_consultations: int
    testnet_consultations: int
    paper_consultations: int
    testnet_metrics: dict[str, Any]
    paper_metrics: dict[str, Any]
    drawdown_distribution: dict[str, Any]


class TestnetComparisonResponse(BaseModel):
    """Detailed side-by-side performance and strategy divergence analysis."""
    comparison_timestamp: str
    testnet_summary: dict[str, Any]
    paper_summary: dict[str, Any]
    strategy_divergence: list[dict[str, Any]]
    recommendations_summary: str
